# Generated by Django 2.1.5 on 2019-01-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
