# Generated by Django 2.1.5 on 2019-01-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_column_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='archived',
        ),
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
